SELECT  Email, FirstName as 'First Name', LastName as 'Last Name', Genre.Name
FROM CUSTOMER 
JOIN INVOICE  ON Customer.CUSTOMERID = Invoice.CUSTOMERID
JOIN INVOICELINE  ON InvoiceLine.INVOICELINEID =Invoice.INVOICEID
JOIN TRACK  ON InvoiceLine.TRACKID = Track.TRACKID
JOIN GENRE  ON Track.GENREID = Genre.GENREID
WHERE Genre.NAME = 'Rock'
ORDER BY 1;

#Shorthand variables
SELECT AR.NAME, COUNT(T.NAME)
FROM TRACK T
JOIN GENRE G ON T.GENREID = G.GENREID
JOIN ALBUM AL ON AL.ALBUMID = T.ALBUMID
JOIN ARTIST AR ON AR.ARTISTID = AL.ARTISTID
WHERE G.NAME = 'Rock'
GROUP BY 1
ORDER BY 2 DESC

SELECT Y.NAME AS ARTIST_NAME,SUM(TOTAL) AS GRAND_TOTAL
  FROM
  (SELECT X.NAME,X.UNITPRICE * X.QUANTITY AS TOTAL
           FROM
              (SELECT AR.NAME,
                             IL.UNITPRICE,
                             IL.QUANTITY
                    FROM ARTIST AR
                    JOIN ALBUM AL ON AR.ARTISTID = AL.ARTISTID
                    JOIN TRACK T ON AL.ALBUMID = T.ALBUMID
                    JOIN INVOICELINE IL ON T.TRACKID = IL.TRACKID
                    ORDER BY 1 DESC) AS X) AS Y
  GROUP BY 1
  ORDER BY 2 DESC
  LIMIT 1
